/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sw;

import java.awt.EventQueue;
import java.awt.Image;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Msys
 */
public class Addpost extends javax.swing.JFrame {

    /**
     * Creates new form Addpost
     */
    String filename=null;
    public Addpost() {
        initComponents();
        //place main frame in center
         super.pack();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadesc = new javax.swing.JTextArea();
        jTextFieldhashtag = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonupload = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelchoosefile = new javax.swing.JLabel();
        jLabelsefile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1018, 768));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainpage.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 250, 760));

        jPanel3.setBackground(new java.awt.Color(18, 33, 139));

        jScrollPane1.setBorder(null);

        jTextAreadesc.setColumns(20);
        jTextAreadesc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextAreadesc.setForeground(new java.awt.Color(18, 33, 139));
        jTextAreadesc.setRows(5);
        jTextAreadesc.setText("Enter your Description");
        jTextAreadesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 33, 139), 3));
        jTextAreadesc.setSelectionColor(new java.awt.Color(244, 216, 19));
        jTextAreadesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreadescFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreadescFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreadesc);

        jTextFieldhashtag.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldhashtag.setForeground(new java.awt.Color(18, 33, 139));
        jTextFieldhashtag.setText("#Hashtag");
        jTextFieldhashtag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 33, 139), 3));
        jTextFieldhashtag.setSelectionColor(new java.awt.Color(244, 216, 19));
        jTextFieldhashtag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldhashtagFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldhashtagFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addComponent(jTextFieldhashtag))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextFieldhashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 800, 550));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButtonupload.setBackground(new java.awt.Color(18, 33, 139));
        jButtonupload.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonupload.setForeground(new java.awt.Color(255, 255, 255));
        jButtonupload.setText("Upload");
        jButtonupload.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 33, 139), 4, true));
        jButtonupload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonuploadActionPerformed(evt);
            }
        });

        jButtoncancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtoncancel.setForeground(new java.awt.Color(18, 33, 139));
        jButtoncancel.setText("Cancel");
        jButtoncancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtoncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 33, 139), 4));

        jLabelchoosefile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelchoosefile.setForeground(new java.awt.Color(18, 33, 139));
        jLabelchoosefile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelchoosefile.setText("Click here to add new file");
        jLabelchoosefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelchoosefile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelchoosefileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelsefile, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelchoosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelsefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelchoosefile, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtoncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonupload, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtoncancel)
                    .addComponent(jButtonupload, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 556, 800, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jTextAreadescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreadescFocusGained
        // TODO add your handling code here:
         if(jTextAreadesc.getText().trim().equals("Enter your Description"))
            jTextAreadesc.setText("");
    }//GEN-LAST:event_jTextAreadescFocusGained

    private void jTextAreadescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreadescFocusLost
        // TODO add your handling code here:
        if(jTextAreadesc.getText().trim().equals(""))
            jTextAreadesc.setText("Enter your Description");
    }//GEN-LAST:event_jTextAreadescFocusLost

    private void jTextFieldhashtagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldhashtagFocusGained
        // TODO add your handling code here:
         if(jTextFieldhashtag.getText().trim().equals("#Hashtag"))
            jTextFieldhashtag.setText("");
    }//GEN-LAST:event_jTextFieldhashtagFocusGained

    private void jTextFieldhashtagFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldhashtagFocusLost
        // TODO add your handling code here:
        if(jTextFieldhashtag.getText().trim().equals(""))
            jTextFieldhashtag.setText("#Hashtag");
    }//GEN-LAST:event_jTextFieldhashtagFocusLost

    private void jButtonuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonuploadActionPerformed
        // TODO add your handling code here:
          try{
              //******************* open connection with mysql:
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/softwareproject","root","iNEEDtostudy@202");
            
            //********************* insert data into post table:
            System.out.println("filepath new:: "+filename);
            String sql1="insert into post (content,description,username) values (?,?,?)";
            PreparedStatement pstmt1=conn.prepareStatement(sql1);
            pstmt1.setString(1, filename);
            pstmt1.setString(2, jTextAreadesc.getText());
            pstmt1.setString(3, "saja123");
            pstmt1.executeUpdate();
    
            
            //******************** open hashtag table and post hashtag:
            if(!jTextFieldhashtag.getText().equals("#Hashtag") && !jTextFieldhashtag.getText().equals(""))
            {
               //**************** insert data into hashtag table:
                String sql2="insert into hashtag(keyword) values('"+jTextFieldhashtag.getText()+"')";
                PreparedStatement pstmt2=conn.prepareStatement(sql2);
                pstmt2.executeUpdate();
                
                //*************** open post and hashtag tables to get postid and hashtagid:
                Statement st1=conn.createStatement();
                String sql3="select * from post";
                ResultSet rs1=st1.executeQuery(sql3);
                String idpost=null;
                while(rs1.next()){
                    idpost=String.valueOf(rs1.getInt("idpost"));
                }
                
                 Statement st2=conn.createStatement();
                String sql4="select * from hashtag";
                ResultSet rs2=st2.executeQuery(sql4);
                String idhastag=null;
                while(rs2.next()){
                    idhastag=String.valueOf(rs2.getInt("idhashtag"));
                }
                 
                //********************* insert data into post_hashtag table:
                String sql5="insert into post_hashtag (idpost,idhashtag)values ('"+idpost+"','"+idhastag+"')";
                PreparedStatement pstmt3=conn.prepareStatement(sql5);
                pstmt3.executeUpdate();
                
            }
            
            
            //*********************** change scale for icon to fit the label:
       
        ImageIcon imgicon=new ImageIcon("../image/party.png");
        Image img=imgicon.getImage();
        Image imgscale=img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgscale);
        
        
         //***************** cahnge Icon for Joptionpane:
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }

                ImageIcon icon = new ImageIcon(LogIn.class.getResource("/image/party.jpg"));
                JOptionPane.showMessageDialog(
                        null,
                        "Uploaded Succsffully!",
                        "State", JOptionPane.PLAIN_MESSAGE,
                        icon);
                  dispose();
               
            }
        });
        
       
            //******************** close addpost frame then close connection:
            conn.close();
          
           

        }catch(Exception e)
        {
              JOptionPane.showMessageDialog(null,e);
              System.out.println(e);
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonuploadActionPerformed

    private void jLabelchoosefileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelchoosefileMouseClicked
        // TODO add your handling code here:
       JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        filename=file.getAbsolutePath();
        System.out.println("file path: "+filename);
        jLabelchoosefile.setText("");
        //*********************** change scale for icon to fit the label:
        Icon icon=new ImageIcon(filename);
        ImageIcon imgicon=new ImageIcon(filename);
        Image img=imgicon.getImage();
        Image imgscale=img.getScaledInstance(jLabelsefile.getWidth(), jLabelsefile.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgscale);
        jLabelsefile.setIcon(scaledIcon);
    }//GEN-LAST:event_jLabelchoosefileMouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addpost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addpost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelchoosefile;
    private javax.swing.JLabel jLabelsefile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreadesc;
    private javax.swing.JTextField jTextFieldhashtag;
    // End of variables declaration//GEN-END:variables
}
